apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLczhZMG9vbUttNzRnZktMRnJmCmNJRmZ2SkdMdy9iLzZrZFhxMzNMVllZUGhjaFEzN2Q0RDdvR2V4dFlzZ29jNHExNkZ4Umd3Z1ZRYWNzNDJlMEsKckhZYldLbnhRaS9uU0ZuUWpVbkkzSW1nN1pvcUYrRnJFeks5TUNOaVlKbkpFdmhFSVljRk9uN09VTzZEWVF3NApORVR5bFJLZXY3azdiRGtxZytZSkg1ZmZSWTJRanJRUW9CaW5NdFBhV1hwODhEcjhwaWw3L29pRW9kbnJqUnlzCmV0L003R1dVdkdqYUVMSTAwekFUb1h2cnl4SUlONzlRNURhZU8rY1M0a21Gdlc1dHp5dWZZMzg2SXVQU0FWTloKQ3lrQzZQN3hQbG91Q1g3UWh1UjNTQWY0eXViVzQ3ZDVUMzNERlRJZzV5ZlVTV25OWlZmNXdHQWsvMlhJTnRreQpCUVVDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUEwemVMQWN0VFpybkMvd0ZnKzBjZEpVRCtCClpUamVzRi9iVTRkdlp3elROeHYyakhVc1ZrUDZ3N0Zkc3hzaXVtaEZObmJIOW5xTFg4M2hFNEVFeDVtM0duWnkKVHgwcEM5ZlF5NDkvcGs3YVVyMDBINjAzaE1tMVh4YXJlMlROMWtJZGU5azZ5SjllK2EwRkhwa3NWcHZDZlhnbwpKcTVwb3NxSG5NUjZ4VFpETHB3NmpTZ0xjVGxjRTFvd0ltWE0yNGc0VTNLaVR4eDZWTjVObC8ydlhPcWVHeU82CnVTeER0S2srMGZZTjgzN01RZGFkQlU5bVpZdHQvWWwzQzlLZkt4MEV0cFhmT2w0elZmcWNqUllRbXp6ejFJRWwKMWtuSWpjaFBYcXA5RlVHNHhJRHllZEk2aTJ3dzROZllRWTNrUDUvRjJydEF1SE84RmFEN3REUXIxR1FxCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
    - digital signature
    - key encipherment
    - client auth
