apiVersion: v1
kind: Secret
metadata:
  name: node-secret
type: Opaque
data:
  twitter-consumer-key: "output from [echo -n "your key" | base64]"
  twitter-consumer-secret: "output from [echo -n "your secret" | base64]"
  mongo-url: "output from [echo -n "mongodb://mongo:27017/sanata" | base64]"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: node
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container
        image: gcr.io/sanata-prod/sanata-srv
        ports:
        - containerPort: 8080
        env:
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: node-secret
              key: twitter-consumer-key
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: node-secret
              key: twitter-consumer-secret
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: node-secret
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: gcr.io/sanata-prod/sanata-web
        ports:
        - containerPort: 80
